### ISSUE TITLE
Idea: Actual Alexa Integration

### ISSUE THREAD

**Issue by ghost** [hdurdle/alexa-cats#2]
Hey man, love the work. real nice.

Having trouble actually integrating this into alexa, and using alexa as the back end server oppose to hosting your own. Any chance we can rejig the server code, or dupe it, to allow Alexa hosting functionality. I feel like the current set up is a huge barrier to entry to most people.

Cheers

**Comment by hdurdle** [comment]
Absolutely. Fork it and go for it! If you can add config to choose local or Alexa hosted that'd be great. I'll accept any PR that doesn't break it for me. 😃

**Comment by spikysimonw** [comment]
I guess this never happened? 

Shame.. would be ideal if could be Alexa hosted, while a local docker is easy enough to spin up there's obviously the additional config overhead of reverse SSL proxying, certs etc.

**Comment by spikysimonw** [comment]
Follow-up: works fine as-is using Alexa Lambda function hosting.
(troubleshooting/debugging with this setup is a hassle.. but that's another story)
